cfg:
  sample_rate: 16000
  compute_eval_loss: true
  log_prediction: true
  skip_nan_grad: true
  aligner_type: ar
  label_smoothing: 0.1
  aux_nonar_loss_weight: 0.0
  model_defaults:
    enc_hidden: 256
    pred_hidden: 320
    joint_hidden: 320
  train_ds:
    manifest_filepath: /home/hainanx/Workplace/data/librispeech/train_clean_360.json
    sample_rate: 16000
    batch_size: 8
    shuffle: true
    num_workers: 4
    pin_memory: true
    max_duration: 20.0
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
  validation_ds:
    manifest_filepath: /home/hainanx/Workplace/data/librispeech/dev_clean.json
    sample_rate: 16000
    batch_size: 8
    shuffle: false
    use_start_end_token: false
    num_workers: 4
    pin_memory: true
  test_ds:
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 8
    shuffle: false
    use_start_end_token: false
    num_workers: 4
    pin_memory: true
  tokenizer:
    dir: /home/hainanx/Workplace/NeMo_ord_sync_d146_current/local_tokenizers/tokenizer_spe_bpe_v128
    type: bpe
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 16000
    normalize: per_feature
    window_size: 0.025
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
    pad_to: 0
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 5
    freq_width: 27
    time_width: 0.05
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: 80
    feat_out: -1
    n_layers: 8
    d_model: 256
    subsampling: striding
    subsampling_factor: 4
    subsampling_conv_channels: -1
    causal_downsampling: false
    reduction: null
    reduction_position: null
    reduction_factor: 1
    ff_expansion_factor: 4
    self_attention_model: rel_pos
    n_heads: 4
    att_context_size:
    - -1
    - -1
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000
    conv_kernel_size: 31
    conv_norm_type: batch_norm
    conv_context_size: null
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1
    stochastic_depth_drop_prob: 0.0
    stochastic_depth_mode: linear
    stochastic_depth_start_layer: 1
  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    normalization_mode: null
    random_state_sampling: false
    blank_as_pad: true
    prednet:
      pred_hidden: 320
      pred_rnn_layers: 1
      t_max: null
      dropout: 0.2
  joint:
    _target_: nemo.collections.asr.modules.AlignerJoint
    log_softmax: null
    jointnet:
      joint_hidden: 320
      activation: relu
      dropout: 0.2
  ctc_head:
    hidden: null
    activation: relu
    dropout: 0.0
  decoding:
    aligner_type: ar
    max_symbols: null
  optim:
    name: adamw
    lr: 0.0003
    betas:
    - 0.9
    - 0.98
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: 200
      warmup_ratio: null
      min_lr: 1.0e-06
  labels:
  - <unk>
  - ▁t
  - he
  - ▁a
  - ▁the
  - in
  - ▁w
  - ▁s
  - ▁o
  - re
  - nd
  - ▁h
  - ▁b
  - er
  - ▁m
  - ou
  - it
  - ▁f
  - ▁c
  - is
  - ed
  - at
  - ▁and
  - ▁of
  - en
  - ▁to
  - ing
  - 'on'
  - ▁p
  - ▁th
  - ▁d
  - or
  - es
  - ▁l
  - ▁in
  - an
  - ▁he
  - as
  - ▁n
  - ar
  - ll
  - ▁g
  - ▁i
  - ad
  - ▁e
  - le
  - om
  - ▁be
  - ot
  - ut
  - ic
  - ow
  - ▁it
  - ly
  - ▁wh
  - se
  - ▁was
  - ve
  - ld
  - st
  - ▁on
  - ▁that
  - gh
  - ▁y
  - ▁u
  - ent
  - al
  - ▁his
  - id
  - ver
  - im
  - ▁we
  - ▁re
  - ir
  - et
  - ith
  - ce
  - ▁with
  - ▁r
  - ion
  - ▁as
  - ▁for
  - ▁st
  - ay
  - ur
  - ▁you
  - ▁had
  - ght
  - ▁not
  - ▁an
  - oo
  - her
  - ▁at
  - ter
  - ▁is
  - ▁ha
  - ac
  - ▁her
  - ▁se
  - ▁but
  - ▁
  - e
  - t
  - a
  - o
  - 'n'
  - i
  - h
  - s
  - r
  - d
  - l
  - u
  - m
  - c
  - w
  - f
  - g
  - 'y'
  - p
  - b
  - v
  - k
  - ''''
  - x
  - q
  - j
  - z
  target: nemo.collections.asr.models.aligner_models.EncDecAlignerBPEModel
  nemo_version: 2.8.0rc0
